-- Grocery Store Management SQL Queries

use Grocery_Store_management;

-- Customer Insights
-- 1. How many unique customers have placed orders?
SELECT COUNT(DISTINCT Customer_ID) AS Unique_Customers
FROM orders;


-- 2. Which customers have placed the highest number of orders?
SELECT c.customer_ID,c.customer_Name,COUNT(o.Order_ID) AS order_count
FROM Customers AS c
JOIN Orders AS o
ON c.customer_ID = o.customer_ID
GROUP BY c.customer_ID,c.customer_Name
ORDER BY order_count DESC
limit 1;

	
-- 3. What is the total and average purchase value per customer?
SELECT c.Customer_ID,c.customer_Name,
SUM(Total_price) AS Total_Purchase_Value,
ROUND(AVG(Total_Price),2) AS Average_Purchase_Value
FROM Customers AS c
JOIN Orders AS o
ON c.customer_ID = o.customer_ID
JOIN Order_details AS od
ON od.Order_ID = o.Order_ID
GROUP BY c.Customer_ID,c.customer_Name;


-- 4. Who are the top 5 customers by total purchase amount?
SELECT c.Customer_ID,c.customer_Name,
SUM(Total_price) AS Total_Purchase_Amount
FROM Customers AS c
JOIN Orders AS o
ON c.customer_ID = o.customer_ID
JOIN Order_details AS od
ON od.Order_ID = o.Order_ID
GROUP BY c.Customer_ID,c.customer_Name
ORDER BY Total_Purchase_Amount DESC
limit 5;

-- Product Performance

-- 5. How many products exist in each category?
SELECT ca.Category_ID,ca.Category_Name,
COUNT(p.Product_ID) AS Total_product_count
FROM categories AS ca
JOIN products AS p
on ca.Category_ID = p.Category_ID
GROUP BY ca.Category_ID,ca.Category_Name;


-- 6. What is the average price of products by category?
SELECT ca.Category_ID,ca.Category_Name,
AVG(p.Price) AS Average_price
FROM categories AS ca
JOIN products AS p
ON ca.Category_ID = p.Category_ID
GROUP BY ca.Category_ID,ca.Category_Name;

-- 7. Which products have the highest total sales volume (by quantity)?
SELECT p.Product_Name,
SUM(od.Quantity) AS Hightest_sales
FROM products as p
JOIN order_details as od
on p.Product_ID = od.Product_ID
GROUP BY p.Product_Name
ORDER BY Hightest_sales DESC
LIMIT 1;


-- 8. What is the total revenue generated by each product?
SELECT p.Product_Name,
SUM(od.Total_Price) AS Total_revenue
FROM products AS p
JOIN order_details AS od
ON p.Product_ID = od.Product_ID
GROUP BY p.Product_Name;


-- 9. How do product sales vary by category and supplier?
SELECT c.category_Name,s.Supplier_Name,
SUM(od.Total_Price) as Total_Sales
FROM categories AS c
JOIN products AS p
ON c.Category_ID = p.Category_ID
JOIN supplier AS s
on s.Supplier_ID = p.Supplier_ID
JOIN order_details AS od
ON od.Product_ID = p.Product_ID
GROUP BY c.category_Name,s.Supplier_Name
ORDER BY c.category_Name,Total_Sales DESC;

-- Sales and orders

-- 10. How many orders have been placed in total?
SELECT 
    COUNT(Order_ID) AS Total_Orders
FROM
    orders;


-- 11. What is the average value per order?
SELECT 
    SUM(Total_Price) / COUNT(DISTINCT order_ID) AS Avg_price_per_order
FROM
    order_details;


-- 12. On which dates were the most orders placed?
SELECT Order_Date,COUNT(Order_ID)  AS Order_count 
FROM orders
GROUP BY order_Date
ORDER BY Order_count DESC;


-- 13. What are the monthly trends in order volume and revenue?
SELECT MONTH(STR_TO_DATE(Order_Date,"%m/%d/%Y")) AS Month_number,
COUNT(DISTINCT o.order_ID) AS Order_volume,
SUM(od.Total_Price) AS Total_revenue
FROM Orders AS o
JOIN Order_details AS od
ON o.Order_ID = od.Order_ID
GROUP BY Month_number
ORDER BY Month_number;


-- 14. How do order patterns vary across weekdays and weekends?
select 
CASE
	WHEN DAYNAME(STR_TO_DATE(Order_Date,"%m/%d/%Y")) IN ("saturday","Sunday") THEN "WEEKEND"
    ELSE "WEEKDAY"
END AS day_category,
COUNT(DISTINCT o.order_ID) AS Order_count,
SUM(od.Total_Price) AS Total_revenue
FROM orders AS o
JOIN Order_details AS od
ON o.Order_ID = od.Order_ID
GROUP BY day_category;


--  4 Supplier Contribution

-- 15. How many suppliers are there in the database?
SELECT 
    COUNT(Supplier_ID) AS Supplier_Count
FROM
    supplier;
    

-- 16. Which supplier provides the most products?
SELECT s.Supplier_ID,s.Supplier_Name,
COUNT(p.Product_ID) AS product_count
FROM supplier AS s
JOIN products AS p
ON s.supplier_ID = p.supplier_ID
GROUP BY s.Supplier_ID,s.Supplier_Name
ORDER BY product_count DESC
LIMIT 1;


-- 17. What is the average price of products from each supplier?
SELECT s.Supplier_ID,s.Supplier_Name,
ROUND(AVG(p.Price),2) AS Avg_Price
FROM supplier AS s
JOIN products AS p
ON s.supplier_ID = p.supplier_ID
GROUP BY s.Supplier_ID,s.Supplier_Name;


-- 18. Which suppliers contribute the most to total product sales (by revenue)?
SELECT s.Supplier_ID,s.Supplier_Name,
SUM(od.Total_Price) AS Total_Product_Sales
FROM supplier AS s
JOIN products AS p
ON s.supplier_ID = p.supplier_ID
JOIN order_details AS od
ON od.product_ID = p.product_ID
GROUP BY s.Supplier_ID,s.Supplier_Name
ORDER BY Total_Product_Sales DESC
LIMIT 1;

--  Employee Performance
-- 19. How many employees have processed orders?
SELECT COUNT(DISTINCT Employee_ID)  AS Employee_count
FROM orders;


-- 20. Which employees have handled the most orders?
SELECT e.Employee_ID,e.Employee_Name,
COUNT(o.Order_ID) AS order_count
FROM Employees AS e
JOIN Orders AS o
ON e.Employee_ID = o.Employee_ID
GROUP BY e.Employee_ID,e.Employee_Name
ORDER BY order_count DESC
LIMIT 1;


-- 21. What is the total sales value processed by each employee?
SELECT e.Employee_ID,e.Employee_Name,
SUM(od.Total_Price) AS Total_sales
FROM Employees AS e
JOIN Orders AS o
ON e.Employee_ID = o.Employee_ID
JOIN Order_details AS od
ON od.Order_ID = o.Order_ID
GROUP BY e.Employee_ID,e.Employee_Name;


-- 22. What is the average order value handled per employee?
SELECT e.Employee_ID,e.Employee_Name,
SUM(od.Total_Price) / COUNT(DISTINCT od.order_ID) AS Average_order_value
FROM Employees AS e
JOIN Orders AS o
ON e.Employee_ID = o.Employee_ID
JOIN Order_details AS od
ON od.Order_ID = o.Order_ID
GROUP BY e.Employee_ID,e.Employee_Name
ORDER BY Average_order_value DESC;

-- Order Details Deep Dive

-- 23. What is the relationship between quantity ordered and total price?
SELECT Quantity,
AVG(Total_Price) AS Avg_total_price,
SUM(Total_Price) AS Total_sales
FROM Order_details
GROUP BY Quantity
ORDER BY  Quantity; 


-- 24. What is the average quantity ordered per product?
SELECT p.Product_ID,p.Product_Name,
AVG(od.Quantity) AS Average_Quantity_Ordered
FROM products AS P
JOIN Order_details AS od 
ON p.Product_ID = od.Product_ID
GROUP BY p.Product_ID,p.Product_Name
ORDER BY Average_Quantity_Ordered DESC;


-- 25. How does the unit price vary across products and orders?
SELECT 
	p.Product_ID,p.Product_Name,o.order_ID,od.Each_Price AS Unit_Price,
    MIN(od.Each_Price) OVER(PARTITION BY p.Product_ID) AS Minimum_Unit_Price,
    MAX(od.Each_Price) OVER(PARTITION BY p.Product_ID) AS Maximum_Unit_Price
    FROM products AS P
JOIN Order_details AS od 
ON p.Product_ID = od.Product_ID
JOIN Orders AS o
ON o.Order_ID = od.Order_ID
ORDER BY p.product_ID,o.order_ID;
